{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-oauth2-demo.fullname" . }}
  labels:
    {{- include "mcp-oauth2-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.oidcClientSecret | quote }}
{{- end }}
